insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (2, 'Black Currants', 'Glavno jelo', 29.0, 645, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (3, 'Muffin - Mix - Mango Sour Cherry', 'Desert', 29.25, 250, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (4, 'Spinach - Baby', 'Predjelo', 35.44, 1872, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (5, 'Cheese - Stilton', 'Glavno jelo', 42.35, 432, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (6, 'Steampan - Foil', 'Glavno jelo', 15.81, 1412, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (7, 'Spic And Span All Purpose', 'Predjelo', 14.09, 666, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (8, 'Soup Campbells Beef With Veg', 'Glavno jelo', 48.3, 1075, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (9, 'Onions Granulated', 'Glavno jelo', 41.35, 796, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (10, 'Cleaner - Lime Away', 'Desert', 40.32, 1437, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (11, 'Bread - Frozen Basket Variety', 'Desert', 22.54, 443, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (12, 'Beef - Striploin', 'Predjelo', 31.25, 694, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (13, 'Appetizer - Tarragon Chicken', 'Glavno jelo', 34.95, 1159, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (14, 'Paper - Brown Paper Mini Cups', 'Predjelo', 23.02, 213, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (15, 'Basil - Fresh', 'Predjelo', 48.93, 1812, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (16, 'Wine - Rubyport', 'Glavno jelo', 39.94, 315, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (17, 'Towel Multifold', 'Desert', 12.91, 1778, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (18, 'Veal - Bones', 'Glavno jelo', 19.64, 827, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (19, 'Longos - Chicken Curried', 'Desert', 29.25, 315, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (20, 'Turnip - White, Organic', 'Desert', 17.89, 1165, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (21, 'Oil - Truffle, White', 'Desert', 46.84, 1903, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (22, 'Muffin Chocolate Individual Wrap', 'Glavno jelo', 10.32, 1707, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (23, 'Beer - Creemore', 'Glavno jelo', 8.28, 1117, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (24, 'V8 - Tropical Blend', 'Predjelo', 21.13, 1124, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (25, 'Cheese - Pied De Vents', 'Desert', 46.1, 1316, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (26, 'Grenadine', 'Desert', 34.05, 1905, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (27, 'Cheese - Provolone', 'Glavno jelo', 44.03, 843, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (28, 'Cup - 4oz Translucent', 'Glavno jelo', 16.01, 340, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (29, 'Pepper - Cayenne', 'Predjelo', 21.7, 911, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (30, 'Scallops - U - 10', 'Glavno jelo', 45.97, 1731, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (31, 'Versatainer Nc - 8288', 'Predjelo', 22.88, 1207, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (32, 'Pasta - Rotini, Dry', 'Desert', 36.34, 1363, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (33, 'Rambutan', 'Desert', 6.72, 798, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (34, 'Oil - Shortening - All - Purpose', 'Predjelo', 38.49, 1096, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (35, 'Shrimp - Black Tiger 16/20', 'Predjelo', 23.62, 628, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (36, 'Sproutsmustard Cress', 'Desert', 20.64, 1035, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (37, 'Puree - Blackcurrant', 'Glavno jelo', 45.8, 361, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (38, 'Wine - Taylors Reserve', 'Predjelo', 25.55, 824, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (39, 'Dried Apple', 'Predjelo', 13.28, 495, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (40, 'Longos - Lasagna Beef', 'Predjelo', 30.98, 1545, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (41, 'Soup - Tomato Mush. Florentine', 'Desert', 45.5, 1180, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (42, 'Wine - Mas Chicet Rose, Vintage', 'Desert', 42.7, 304, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (43, 'Chilli Paste, Ginger Garlic', 'Glavno jelo', 38.46, 979, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (44, 'Mushroom - Shitake, Dry', 'Predjelo', 20.78, 1107, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (45, 'Lumpfish Black', 'Desert', 22.71, 317, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (46, 'Mousse - Mango', 'Desert', 29.35, 1291, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (47, 'Veal - Insides Provini', 'Glavno jelo', 25.15, 1061, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (48, 'Shrimp - 16/20, Peeled Deviened', 'Desert', 23.91, 1541, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (49, 'Wine - Prem Select Charddonany', 'Desert', 47.49, 1875, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (50, 'Silicone Parch. 16.3x24.3', 'Predjelo', 14.57, 924, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (51, 'Nantucket Apple Juice', 'Desert', 43.88, 1391, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (52, 'Arizona - Green Tea', 'Glavno jelo', 18.59, 892, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (53, 'Pasta - Tortellini, Fresh', 'Predjelo', 41.98, 1978, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (54, 'Coffee - Flavoured', 'Desert', 16.79, 1637, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (55, 'Cheese - Cambozola', 'Predjelo', 5.5, 1002, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (56, 'Puree - Passion Fruit', 'Desert', 44.97, 1165, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (57, 'Cheese - Brie Roitelet', 'Predjelo', 5.97, 870, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (58, 'Wine - Mas Chicet Rose, Vintage', 'Predjelo', 18.85, 1021, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (59, 'V8 - Berry Blend', 'Desert', 9.56, 393, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (60, 'Cookie Trail Mix', 'Predjelo', 21.45, 1656, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (61, 'Watercress', 'Desert', 42.96, 334, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (62, 'Turkey - Breast, Boneless Sk On', 'Desert', 20.76, 1042, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (63, 'Bread - Roll, Canadian Dinner', 'Predjelo', 24.74, 1424, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (64, 'Crab - Dungeness, Whole, live', 'Glavno jelo', 45.88, 1523, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (65, 'Soup - Campbells Beef Strogonoff', 'Glavno jelo', 34.43, 1109, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (66, 'Flavouring Vanilla Artificial', 'Desert', 26.63, 1439, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (67, 'Beef - Rib Roast, Cap On', 'Desert', 17.03, 482, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (68, 'Bread Base - Italian', 'Glavno jelo', 19.89, 1873, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (69, 'Sauce - Caesar Dressing', 'Predjelo', 27.38, 795, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (70, 'Wine - Red, Gallo, Merlot', 'Desert', 12.65, 684, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (71, 'Bread - Triangle White', 'Glavno jelo', 49.13, 244, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (72, 'Puree - Raspberry', 'Glavno jelo', 35.21, 839, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (73, 'Broom And Broom Rack White', 'Desert', 25.94, 403, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (74, 'Fruit Salad Deluxe', 'Desert', 48.75, 611, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (75, 'Isomalt', 'Glavno jelo', 15.22, 884, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (76, 'Pork Salted Bellies', 'Predjelo', 44.76, 1662, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (77, 'Yogurt - Blueberry, 175 Gr', 'Predjelo', 24.59, 477, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (78, 'Coriander - Ground', 'Predjelo', 8.2, 1453, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (79, 'Lamb - Shanks', 'Glavno jelo', 35.5, 1377, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (80, 'Yokaline', 'Glavno jelo', 22.93, 1492, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (81, 'Cheese - Cottage Cheese', 'Desert', 11.64, 1473, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (82, 'Wine - Sauvignon Blanc', 'Predjelo', 32.59, 1036, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (83, 'Nantucket Pine Orangebanana', 'Predjelo', 47.85, 912, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (84, 'Wine - Red, Cabernet Merlot', 'Predjelo', 6.09, 1467, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (85, 'Flour - So Mix Cake White', 'Predjelo', 23.7, 908, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (86, 'Pickles - Gherkins', 'Desert', 26.09, 954, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (87, 'Foil - 4oz Custard Cup', 'Predjelo', 30.77, 1725, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (88, 'Coffee - Espresso', 'Predjelo', 6.35, 956, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (89, 'Ham - Virginia', 'Desert', 14.25, 1079, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (90, 'Wine - Maipo Valle Cabernet', 'Desert', 13.35, 1124, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (91, 'Sauce - Soya, Dark', 'Glavno jelo', 33.53, 1126, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (92, 'Beer - Camerons Cream Ale', 'Predjelo', 49.11, 1514, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (93, 'Potato - Sweet', 'Desert', 14.06, 1551, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (94, 'Gelatine Leaves - Bulk', 'Desert', 35.42, 428, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (95, 'Breakfast Quesadillas', 'Desert', 8.37, 620, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (96, 'Oil - Hazelnut', 'Glavno jelo', 44.7, 1944, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (97, 'Container Clear 8 Oz', 'Glavno jelo', 17.25, 1247, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (98, 'Squash - Sunburst', 'Desert', 42.11, 1596, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (99, 'Filter - Coffee', 'Desert', 34.34, 697, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (100, 'Asparagus - Mexican', 'Desert', 25.86, 948, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (101, 'Longos - Cheese Tortellini', 'Predjelo', 36.41, 249, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (102, 'Veal - Round, Eye Of', 'Desert', 48.2, 344, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (103, 'Chips Potato All Dressed - 43g', 'Glavno jelo', 31.47, 1919, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (104, 'Pork - Backs - Boneless', 'Desert', 18.53, 1396, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (105, 'Pastry - Butterscotch Baked', 'Glavno jelo', 23.14, 1044, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (106, 'Nantucket - Orange Mango Cktl', 'Predjelo', 15.86, 1031, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (107, 'Syrup - Monin, Swiss Choclate', 'Glavno jelo', 5.51, 1135, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (108, 'Cookies - Amaretto', 'Predjelo', 20.47, 305, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (109, 'Fruit Mix - Light', 'Glavno jelo', 44.24, 1659, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (110, 'Chocolate - Pistoles, White', 'Desert', 38.54, 216, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (111, 'Juice - Apple, 341 Ml', 'Desert', 21.72, 681, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (112, 'Triple Sec - Mcguinness', 'Predjelo', 31.42, 724, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (113, 'Rum - Light, Captain Morgan', 'Desert', 39.95, 1126, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (114, 'Honey - Comb', 'Predjelo', 20.78, 1168, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (115, 'Mussels - Cultivated', 'Desert', 7.28, 843, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (116, 'Gelatine Leaves - Bulk', 'Glavno jelo', 6.81, 242, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (117, 'Seabream Whole Farmed', 'Predjelo', 47.91, 426, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (118, 'Soup - Campbells, Classic Chix', 'Desert', 27.19, 1166, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (119, 'Juice - Happy Planet', 'Predjelo', 49.06, 1301, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (120, 'Cheese - Grana Padano', 'Predjelo', 46.21, 1309, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (121, 'Cognac - Courvaisier', 'Desert', 20.52, 902, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (122, 'Beer - Tetleys', 'Desert', 42.71, 1348, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (123, 'Napkin - Beverge, White 2 - Ply', 'Glavno jelo', 40.16, 1781, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (124, 'Pasta - Penne, Lisce, Dry', 'Desert', 32.75, 1254, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (125, 'Quail - Jumbo Boneless', 'Predjelo', 7.71, 1474, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (126, 'Nut - Pistachio, Shelled', 'Glavno jelo', 49.23, 594, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (127, 'Vermouth - Sweet, Cinzano', 'Glavno jelo', 23.25, 1316, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (128, 'Butter - Unsalted', 'Glavno jelo', 45.79, 1449, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (129, 'Oranges', 'Predjelo', 46.16, 1852, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (130, 'Mushrooms - Honey', 'Desert', 23.78, 1293, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (131, 'Beef - Eye Of Round', 'Desert', 40.12, 646, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (132, 'Island Oasis - Strawberry', 'Predjelo', 35.31, 1625, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (133, 'Flour Dark Rye', 'Predjelo', 30.22, 1428, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (134, 'Pork - Sausage Casing', 'Desert', 5.97, 795, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (135, 'Mushrooms - Honey', 'Predjelo', 48.24, 1800, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (136, 'Straw - Regular', 'Predjelo', 31.86, 367, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (137, 'Squash - Guords', 'Predjelo', 25.03, 240, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (138, 'Table Cloth 81x81 White', 'Glavno jelo', 24.83, 1588, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (139, 'Pork - Sausage, Medium', 'Glavno jelo', 10.16, 414, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (140, 'Wine - Cahors Ac 2000, Clos', 'Desert', 47.13, 746, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (141, 'Pepper - Red Bell', 'Desert', 26.05, 1415, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (142, 'Truffle Shells - White Chocolate', 'Predjelo', 32.65, 381, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (143, 'Pepper - Chilli Seeds Mild', 'Glavno jelo', 44.19, 797, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (144, 'Pastry - Chocolate Chip Muffin', 'Glavno jelo', 28.8, 521, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (145, 'Muffin Mix - Raisin Bran', 'Predjelo', 13.84, 1025, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (146, 'Pepper - Black, Ground', 'Predjelo', 17.3, 757, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (147, 'Oyster - In Shell', 'Predjelo', 31.23, 193, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (148, 'Muffin Carrot - Individual', 'Desert', 10.85, 1772, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (149, 'Potatoes - Purple, Organic', 'Glavno jelo', 13.23, 476, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (150, 'Pears - Fiorelle', 'Glavno jelo', 17.22, 1862, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (151, 'Mousse - Mango', 'Predjelo', 32.38, 789, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (152, 'Beef - Tenderloin', 'Desert', 46.05, 1169, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (153, 'Beer - Heinekin', 'Glavno jelo', 31.24, 917, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (154, 'Bread - Multigrain Oval', 'Desert', 39.44, 1901, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (155, 'Zucchini - Green', 'Desert', 20.06, 298, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (156, 'Nut - Pecan, Pieces', 'Predjelo', 16.22, 1578, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (157, 'Plate Pie Foil', 'Glavno jelo', 41.38, 1129, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (158, 'Mini - Vol Au Vents', 'Predjelo', 45.93, 762, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (159, 'Bread - Rolls, Rye', 'Desert', 10.28, 153, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (160, 'Soup - Campbells Beef Noodle', 'Glavno jelo', 9.79, 791, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (161, 'Walkers Special Old Whiskey', 'Desert', 43.8, 916, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (162, 'Puree - Guava', 'Desert', 12.37, 1084, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (163, 'Veal - Insides, Grains', 'Desert', 7.37, 709, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (164, 'Island Oasis - Ice Cream Mix', 'Desert', 10.36, 1267, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (165, 'Rice - Wild', 'Glavno jelo', 19.49, 1545, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (166, 'Bread - Pullman, Sliced', 'Predjelo', 42.15, 690, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (167, 'Cabbage - Savoy', 'Desert', 29.21, 453, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (168, 'Melon - Cantaloupe', 'Predjelo', 22.94, 338, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (169, 'Carbonated Water - Peach', 'Desert', 43.79, 1167, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (170, 'Cocoa Feuilletine', 'Glavno jelo', 31.12, 1876, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (171, 'Longos - Lasagna Beef', 'Predjelo', 13.58, 824, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (172, 'Pear - Halves', 'Glavno jelo', 7.33, 237, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (173, 'Limes', 'Desert', 29.31, 1928, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (174, 'Pastry - Carrot Muffin - Mini', 'Glavno jelo', 37.35, 416, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (175, 'Soupfoamcont12oz 112con', 'Glavno jelo', 20.03, 1353, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (176, 'Chinese Foods - Pepper Beef', 'Predjelo', 8.98, 232, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (177, 'Napkin White', 'Desert', 11.47, 1867, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (178, 'Bok Choy - Baby', 'Predjelo', 41.1, 1353, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (179, 'Tart Shells - Savory, 3', 'Desert', 27.01, 724, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (180, 'Sausage - Blood Pudding', 'Predjelo', 43.82, 1807, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (181, 'Plaintain', 'Desert', 26.28, 535, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (182, 'Beef - Kobe Striploin', 'Predjelo', 6.89, 298, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (183, 'Pepper - Julienne, Frozen', 'Desert', 10.95, 1855, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (184, 'Doilies - 5, Paper', 'Desert', 38.51, 958, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (185, 'Fish - Scallops, Cold Smoked', 'Predjelo', 18.94, 1058, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (186, 'Coffee Cup 16oz Foam', 'Predjelo', 17.28, 615, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (187, 'Compound - Pear', 'Glavno jelo', 10.24, 251, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (188, 'Lettuce - Mini Greens, Whole', 'Predjelo', 24.45, 585, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (189, 'Cleaner - Pine Sol', 'Glavno jelo', 18.65, 368, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (190, 'Eggwhite Frozen', 'Desert', 20.18, 804, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (191, 'Trueblue - Blueberry Cranberry', 'Desert', 41.28, 1872, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (192, 'Fiddlehead - Frozen', 'Predjelo', 17.24, 978, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (193, 'Mushroom - Lg - Cello', 'Predjelo', 48.83, 1432, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (194, 'Soup - Campbells, Butternut', 'Predjelo', 40.15, 1429, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (195, 'Glass Clear 7 Oz Xl', 'Desert', 48.63, 796, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (196, 'Ice Cream Bar - Hageen Daz To', 'Glavno jelo', 29.63, 764, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (197, 'Beer - Mill St Organic', 'Predjelo', 9.0, 1257, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (198, 'Mangoes', 'Predjelo', 24.42, 250, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (199, 'Bar Special K', 'Desert', 7.57, 898, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (200, 'Food Colouring - Green', 'Desert', 22.85, 526, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (201, 'Lettuce - Romaine', 'Glavno jelo', 11.55, 629, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (202, 'Bread - Dark Rye, Loaf', 'Desert', 25.91, 690, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (203, 'Sauce - Hp', 'Predjelo', 28.97, 1670, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (204, 'Wine - Beringer Founders Estate', 'Glavno jelo', 23.17, 535, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (205, 'Oil - Coconut', 'Glavno jelo', 22.96, 1527, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (206, 'V8 Pet', 'Predjelo', 28.39, 783, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (207, 'Spoon - Soup, Plastic', 'Desert', 13.82, 475, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (208, 'Poppy Seed', 'Predjelo', 9.18, 994, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (209, 'Wine - White, Schroder And Schyl', 'Predjelo', 16.71, 1992, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (210, 'Truffle - Whole Black Peeled', 'Desert', 44.41, 1759, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (211, 'Flour - Corn, Fine', 'Desert', 26.57, 1054, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (212, 'Extract - Rum', 'Predjelo', 11.15, 871, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (213, 'Pasta - Tortellini, Fresh', 'Predjelo', 30.8, 1006, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (214, 'Cheese - Le Cheve Noir', 'Desert', 47.47, 1092, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (215, 'Eggroll', 'Desert', 47.49, 487, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (216, 'Hot Choc Vending', 'Predjelo', 19.05, 1284, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (217, 'Extract - Lemon', 'Desert', 47.2, 1365, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (218, 'Beef - Striploin', 'Desert', 25.2, 1899, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (219, 'Wine - Casablanca Valley', 'Glavno jelo', 19.3, 1042, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (220, 'Everfresh Products', 'Glavno jelo', 44.18, 589, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (221, 'Horseradish - Prepared', 'Desert', 23.17, 650, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (222, 'Chick Peas - Dried', 'Glavno jelo', 35.07, 1815, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (223, 'White Baguette', 'Desert', 31.66, 827, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (224, 'Urban Zen Drinks', 'Predjelo', 23.34, 1245, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (225, 'Cheese - Gorgonzola', 'Desert', 32.33, 1720, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (226, 'Lamb - Sausage Casings', 'Desert', 46.35, 1710, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (227, 'Spice - Montreal Steak Spice', 'Desert', 24.12, 1685, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (228, 'Tart Shells - Savory, 4', 'Desert', 44.96, 773, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (229, 'Cape Capensis - Fillet', 'Glavno jelo', 7.8, 1440, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (230, 'Tray - 12in Rnd Blk', 'Predjelo', 16.08, 1245, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (231, 'Cape Capensis - Fillet', 'Predjelo', 24.82, 1352, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (232, 'Wasabi Paste', 'Desert', 12.2, 577, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (233, 'Aspic - Light', 'Desert', 30.99, 865, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (234, 'Lamb - Loin Chops', 'Predjelo', 18.4, 1128, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (235, 'Wine - Bourgogne 2002, La', 'Glavno jelo', 45.09, 379, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (236, 'Goat - Whole Cut', 'Desert', 25.57, 813, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (237, 'Noodles - Steamed Chow Mein', 'Predjelo', 21.85, 1289, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (238, 'Pasta - Fettuccine, Egg, Fresh', 'Glavno jelo', 36.41, 1643, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (239, 'Salt - Celery', 'Desert', 43.45, 1878, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (240, 'Brandy - Bar', 'Glavno jelo', 45.37, 656, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (241, 'Cherries - Bing, Canned', 'Predjelo', 13.72, 579, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (242, 'Venison - Liver', 'Glavno jelo', 27.58, 1816, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (243, 'Beef - Sushi Flat Iron Steak', 'Predjelo', 39.2, 631, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (244, 'Coriander - Seed', 'Desert', 28.78, 1430, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (245, 'Lentils - Green, Dry', 'Predjelo', 32.76, 1059, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (246, 'Trout - Smoked', 'Desert', 13.84, 1064, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (247, 'Wine - Magnotta - Red, Baco', 'Glavno jelo', 31.26, 1283, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (248, 'Jameson - Irish Whiskey', 'Desert', 31.45, 1128, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (249, 'Sausage - Meat', 'Desert', 40.77, 1139, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (250, 'Puree - Pear', 'Desert', 41.88, 1671, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (251, 'Chocolate - Feathers', 'Glavno jelo', 33.94, 180, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (252, 'Kiwano', 'Glavno jelo', 35.49, 1502, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (253, 'Scallop - St. Jaques', 'Desert', 45.79, 1659, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (254, 'Fish - Bones', 'Predjelo', 37.31, 581, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (255, 'Container Clear 8 Oz', 'Glavno jelo', 38.02, 759, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (256, 'Trout Rainbow Whole', 'Predjelo', 47.96, 1252, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (257, 'Goldschalger', 'Desert', 36.24, 1121, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (258, 'Beer - Moosehead', 'Predjelo', 34.68, 1036, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (259, 'Muffin Hinge 117n', 'Predjelo', 28.46, 1798, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (260, 'Dish Towel', 'Predjelo', 46.57, 1098, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (261, 'Veal - Bones', 'Glavno jelo', 32.35, 1159, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (262, 'Quail - Eggs, Fresh', 'Glavno jelo', 24.29, 1819, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (263, 'Bacardi Raspberry', 'Glavno jelo', 28.14, 193, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (264, 'Higashimaru Usukuchi Soy', 'Glavno jelo', 27.09, 1707, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (265, 'Ice Cream Bar - Hageen Daz To', 'Desert', 32.43, 702, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (266, 'Lettuce - Romaine', 'Desert', 44.37, 1022, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (267, 'Samosa - Veg', 'Desert', 44.29, 605, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (268, 'Scallop - St. Jaques', 'Desert', 7.28, 1954, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (269, 'Cheese - Colby', 'Desert', 6.72, 1458, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (270, 'Dc - Frozen Momji', 'Glavno jelo', 5.38, 293, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (271, 'Gherkin - Sour', 'Glavno jelo', 34.78, 1068, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (272, 'Wine - Cotes Du Rhone Parallele', 'Glavno jelo', 43.45, 1455, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (273, 'Pepper - White, Ground', 'Glavno jelo', 44.0, 972, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (274, 'Nantucket - Orange Mango Cktl', 'Desert', 39.9, 847, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (275, 'Catfish - Fillets', 'Desert', 36.2, 589, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (276, 'Nut - Peanut, Roasted', 'Glavno jelo', 39.83, 615, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (277, 'Sea Bass - Fillets', 'Glavno jelo', 45.29, 244, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (278, 'Huck White Towels', 'Desert', 46.39, 700, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (279, 'Wine - Fontanafredda Barolo', 'Glavno jelo', 44.76, 771, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (280, 'Puree - Raspberry', 'Glavno jelo', 31.75, 1890, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (281, 'Juice - Ocean Spray Kiwi', 'Desert', 26.57, 907, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (282, 'Mushroom - Morel Frozen', 'Glavno jelo', 5.2, 1825, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (283, 'Pork Casing', 'Glavno jelo', 14.42, 458, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (284, 'Soup - Tomato Mush. Florentine', 'Desert', 43.9, 1556, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (285, 'Marjoram - Fresh', 'Desert', 32.98, 582, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (286, 'Milk Powder', 'Glavno jelo', 42.99, 1913, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (287, 'Eel - Smoked', 'Glavno jelo', 45.32, 295, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (288, 'Cheese - Romano, Grated', 'Predjelo', 33.21, 1056, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (289, 'Oats Large Flake', 'Desert', 45.26, 1601, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (290, 'Turnip - White', 'Desert', 35.86, 406, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (291, 'Lettuce - California Mix', 'Predjelo', 26.65, 650, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (292, 'Soup - French Can Pea', 'Glavno jelo', 19.51, 1445, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (293, 'Longan', 'Desert', 39.03, 151, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (294, 'Muffin - Bran Ind Wrpd', 'Predjelo', 11.86, 785, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (295, 'Cheese - Roquefort Pappillon', 'Glavno jelo', 7.71, 325, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (296, 'Rice - Basmati', 'Predjelo', 44.79, 1685, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (297, 'Soap - Hand Soap', 'Glavno jelo', 44.01, 262, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (298, 'Jameson Irish Whiskey', 'Desert', 8.62, 187, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (299, 'Cookie - Oreo 100x2', 'Desert', 8.03, 1779, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (300, 'Garam Masala Powder', 'Desert', 33.59, 1434, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (301, 'Steel Wool', 'Glavno jelo', 22.78, 1681, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (302, 'Jolt Cola', 'Desert', 18.82, 1578, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (303, 'Soup - French Onion, Dry', 'Predjelo', 45.63, 1630, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (304, 'Extract - Raspberry', 'Glavno jelo', 43.47, 1308, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (305, 'Garlic', 'Predjelo', 5.92, 1497, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (306, 'Cup - 4oz Translucent', 'Glavno jelo', 24.88, 1088, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (307, 'Marjoram - Fresh', 'Desert', 18.63, 1832, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (308, 'Garbag Bags - Black', 'Predjelo', 40.1, 1448, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (309, 'Chicken - White Meat, No Tender', 'Glavno jelo', 39.64, 1542, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (310, 'Oil - Shortening,liqud, Fry', 'Glavno jelo', 42.45, 506, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (311, 'Mushroom - Oyster, Fresh', 'Desert', 15.22, 1569, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (312, 'Wine - Jackson Triggs Okonagan', 'Glavno jelo', 6.91, 1925, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (313, 'Soup - Knorr, French Onion', 'Desert', 47.49, 1185, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (314, 'Chicken - Whole', 'Glavno jelo', 19.42, 889, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (315, 'Lobster - Tail 6 Oz', 'Predjelo', 35.89, 456, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (316, 'Water - Perrier', 'Desert', 12.73, 1147, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (317, 'Papayas', 'Predjelo', 16.22, 579, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (318, 'Cookie Dough - Chocolate Chip', 'Desert', 6.92, 531, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (319, 'Gelatine Powder', 'Desert', 28.79, 1746, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (320, 'Langers - Cranberry Cocktail', 'Desert', 39.5, 426, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (321, 'Cookies - Englishbay Oatmeal', 'Predjelo', 49.85, 1244, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (322, 'Ocean Spray - Ruby Red', 'Desert', 11.42, 1651, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (323, 'Wine - Cotes Du Rhone Parallele', 'Predjelo', 31.73, 1097, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (324, 'Sambuca Cream', 'Predjelo', 26.46, 1758, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (325, 'Split Peas - Yellow, Dry', 'Glavno jelo', 6.97, 1429, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (326, 'Wine - Lamancha Do Crianza', 'Predjelo', 35.92, 1811, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (327, 'Egg Patty Fried', 'Predjelo', 15.04, 418, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (328, 'Sauce - Cranberry', 'Glavno jelo', 47.73, 974, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (329, 'Everfresh Products', 'Glavno jelo', 16.19, 986, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (330, 'Mikes Hard Lemonade', 'Desert', 6.45, 744, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (331, 'Butter - Salted, Micro', 'Glavno jelo', 44.13, 1350, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (332, 'Sole - Fillet', 'Glavno jelo', 20.12, 315, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (333, 'Apples - Sliced / Wedge', 'Desert', 28.99, 1671, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (334, 'Island Oasis - Strawberry', 'Glavno jelo', 5.99, 374, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (335, 'Soup - Campbells Beef Noodle', 'Desert', 11.37, 643, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (336, 'Pork Salted Bellies', 'Desert', 43.17, 940, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (337, 'Chicken Breast Wing On', 'Predjelo', 10.33, 873, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (338, 'Celery', 'Desert', 37.54, 1559, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (339, 'Instant Coffee', 'Desert', 16.97, 998, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (340, 'Chocolate - Unsweetened', 'Desert', 41.73, 200, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (341, 'Chinese Foods - Pepper Beef', 'Glavno jelo', 16.89, 1058, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (342, 'Creme De Cacao Mcguines', 'Desert', 39.94, 152, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (343, 'Bread - Triangle White', 'Desert', 42.28, 1343, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (344, 'Wine - Saint - Bris 2002, Sauv', 'Glavno jelo', 49.46, 1133, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (345, 'Baking Soda', 'Desert', 33.21, 1058, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (346, 'Five Alive Citrus', 'Glavno jelo', 18.8, 1370, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (347, 'Cheese - La Sauvagine', 'Glavno jelo', 49.08, 1842, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (348, 'Sobe - Orange Carrot', 'Desert', 43.43, 324, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (349, 'Chicken - Base', 'Desert', 6.77, 420, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (350, 'Clams - Bay', 'Desert', 39.3, 759, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (351, 'Onions - Cippolini', 'Predjelo', 11.3, 738, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (352, 'Wine - Savigny - Les - Beaune', 'Glavno jelo', 34.67, 1850, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (353, 'Food Colouring - Orange', 'Glavno jelo', 6.24, 597, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (354, 'Coffee - Dark Roast', 'Desert', 16.86, 292, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (355, 'Ostrich - Fan Fillet', 'Predjelo', 37.22, 1981, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (356, 'Brandy Cherry - Mcguinness', 'Glavno jelo', 18.79, 1632, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (357, 'Extract - Vanilla,artificial', 'Desert', 31.78, 751, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (358, 'Container - Clear 32 Oz', 'Desert', 49.65, 1211, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (359, 'Cafe Royale', 'Desert', 31.55, 1941, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (360, 'Pepperoni Slices', 'Desert', 8.87, 1089, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (361, 'Teriyaki Sauce', 'Predjelo', 48.31, 320, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (362, 'Cornflakes', 'Predjelo', 25.44, 282, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (363, 'Petite Baguette', 'Desert', 39.83, 1369, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (364, 'Chocolate Eclairs', 'Desert', 13.36, 1514, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (365, 'Anchovy In Oil', 'Predjelo', 24.09, 1711, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (366, 'Nescafe - Frothy French Vanilla', 'Glavno jelo', 47.49, 233, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (367, 'Flavouring - Rum', 'Desert', 46.52, 1302, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (368, 'Smoked Tongue', 'Glavno jelo', 24.99, 1555, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (369, 'Wine - Sauvignon Blanc Oyster', 'Glavno jelo', 40.41, 1108, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (370, 'Cookie - Oreo 100x2', 'Desert', 9.5, 341, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (371, 'Soup - Beef Conomme, Dry', 'Predjelo', 38.4, 1485, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (372, 'Onions - Red', 'Predjelo', 29.07, 393, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (373, 'Soup - Campbells Beef Stew', 'Predjelo', 12.05, 1874, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (374, 'Veal - Tenderloin, Untrimmed', 'Glavno jelo', 7.86, 1358, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (375, 'Amarula Cream', 'Desert', 19.85, 1315, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (376, 'Bread - Italian Sesame Poly', 'Desert', 30.92, 767, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (377, 'Sponge Cake Mix - Chocolate', 'Glavno jelo', 6.85, 1178, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (378, 'Pail - 15l White, With Handle', 'Glavno jelo', 8.21, 1267, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (379, 'Nougat - Paste / Cream', 'Predjelo', 33.87, 1304, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (380, 'Bread - English Muffin', 'Desert', 35.49, 1868, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (381, 'Oyster - In Shell', 'Predjelo', 10.29, 270, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (382, 'Piping - Bags Quizna', 'Glavno jelo', 41.09, 801, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (383, 'Pepper - Black, Crushed', 'Desert', 47.59, 411, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (384, 'Pail With Metal Handle 16l White', 'Desert', 24.56, 970, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (385, 'Appetizer - Shrimp Puff', 'Desert', 33.8, 1708, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (386, 'Pail For Lid 1537', 'Predjelo', 31.59, 1180, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (387, 'Juice - Orange, Concentrate', 'Glavno jelo', 34.13, 796, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (388, 'Veal - Chops, Split, Frenched', 'Desert', 47.25, 1818, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (389, 'Lemon Tarts', 'Desert', 49.54, 887, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (390, 'Bagels Poppyseed', 'Predjelo', 37.75, 954, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (391, 'Plasticforkblack', 'Desert', 32.66, 1175, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (392, 'Wine - Sake', 'Predjelo', 44.78, 410, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (393, 'Sloe Gin - Mcguinness', 'Desert', 9.35, 285, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (394, 'Soup - Beef, Base Mix', 'Desert', 6.3, 310, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (395, 'Glass Clear 7 Oz Xl', 'Desert', 32.39, 1489, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (396, 'Gingerale - Schweppes, 355 Ml', 'Desert', 25.79, 643, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (397, 'Wine - Chianti Classico Riserva', 'Predjelo', 45.0, 1338, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (398, 'Calvados - Boulard', 'Predjelo', 29.8, 1151, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (399, 'Bread - Bistro White', 'Glavno jelo', 10.72, 562, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (400, 'Compound - Mocha', 'Glavno jelo', 36.24, 1432, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (401, 'Wine - Cousino Macul Antiguas', 'Desert', 41.88, 1152, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (402, 'Aromat Spice / Seasoning', 'Desert', 48.5, 566, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (403, 'Nori Sea Weed - Gold Label', 'Glavno jelo', 24.74, 1674, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (404, 'Eel Fresh', 'Predjelo', 36.3, 1000, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (405, 'Ice Cream - Chocolate', 'Glavno jelo', 9.1, 1524, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (406, 'Muffin Mix - Banana Nut', 'Predjelo', 31.93, 493, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (407, 'Jello - Assorted', 'Glavno jelo', 9.16, 1397, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (408, 'Wine - Sicilia Igt Nero Avola', 'Predjelo', 22.94, 1592, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (409, 'Gelatine Leaves - Envelopes', 'Desert', 10.5, 995, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (410, 'Miso Paste White', 'Glavno jelo', 14.99, 1886, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (411, 'Sauce - Roasted Red Pepper', 'Glavno jelo', 43.5, 217, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (412, 'Grapefruit - White', 'Desert', 41.55, 1871, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (413, 'Chambord Royal', 'Desert', 11.44, 1125, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (414, 'Flower - Potmums', 'Desert', 20.98, 1619, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (415, 'Wine - Wyndham Estate Bin 777', 'Desert', 27.26, 1322, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (416, 'Steel Wool', 'Glavno jelo', 32.17, 764, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (417, 'Wine - Redchard Merritt', 'Glavno jelo', 19.21, 368, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (418, 'Onions - Green', 'Glavno jelo', 17.78, 1540, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (419, 'Turkey - Ground. Lean', 'Predjelo', 41.32, 1312, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (420, 'Dawn Professionl Pot And Pan', 'Desert', 15.46, 1176, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (421, 'Yoplait - Strawbrasp Peac', 'Glavno jelo', 35.41, 547, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (422, 'Onion - Dried', 'Predjelo', 41.4, 1231, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (423, 'Filo Dough', 'Predjelo', 10.88, 1067, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (424, 'Icecream - Dibs', 'Desert', 7.92, 1909, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (425, 'Pastry - Trippleberry Muffin - Mini', 'Desert', 34.69, 1735, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (426, 'Cookie Choc', 'Predjelo', 9.12, 974, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (427, 'Cleaner - Lime Away', 'Glavno jelo', 17.06, 1504, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (428, 'Tahini Paste', 'Desert', 19.64, 257, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (429, 'Yoplait Drink', 'Glavno jelo', 37.34, 1413, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (430, 'Potatoes - Mini White 3 Oz', 'Glavno jelo', 40.32, 1072, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (431, 'Mousse - Passion Fruit', 'Glavno jelo', 18.3, 659, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (432, 'Cheese - Manchego, Spanish', 'Desert', 6.31, 1330, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (433, 'Asparagus - Frozen', 'Glavno jelo', 43.65, 926, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (434, 'Yogurt - Raspberry, 175 Gr', 'Predjelo', 28.44, 1435, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (435, 'Drambuie', 'Predjelo', 26.08, 461, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (436, 'Pastry - Key Limepoppy Seed Tea', 'Predjelo', 17.99, 1842, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (437, 'French Pastries', 'Predjelo', 16.34, 250, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (438, 'Cake - Pancake', 'Glavno jelo', 16.74, 1866, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (439, 'Miso Paste White', 'Predjelo', 41.99, 1918, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (440, 'Rum - White, Gg White', 'Predjelo', 37.95, 568, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (441, 'Muffin - Mix - Creme Brule 15l', 'Glavno jelo', 6.17, 152, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (442, 'Magnotta Bel Paese Red', 'Glavno jelo', 12.67, 200, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (443, 'Rice - Long Grain', 'Desert', 17.51, 1994, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (444, 'Asparagus - White, Canned', 'Glavno jelo', 32.05, 897, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (445, 'Dish Towel', 'Glavno jelo', 40.45, 1491, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (446, 'Ice Cream - Vanilla', 'Predjelo', 22.16, 1372, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (447, 'Everfresh Products', 'Glavno jelo', 42.77, 1991, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (448, 'Bagels Poppyseed', 'Predjelo', 19.09, 1248, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (449, 'Cucumber - English', 'Glavno jelo', 42.34, 403, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (450, 'Cookie - Dough Variety', 'Glavno jelo', 21.15, 953, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (451, 'Silicone Paper 16.5x24', 'Desert', 46.59, 1508, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (452, 'Lettuce - Boston Bib', 'Glavno jelo', 46.87, 1685, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (453, 'Contreau', 'Desert', 14.74, 825, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (454, 'Beef - Eye Of Round', 'Predjelo', 32.83, 1131, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (455, 'Juice - Ocean Spray Cranberry', 'Glavno jelo', 8.46, 714, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (456, 'Wasabi Powder', 'Desert', 13.71, 1276, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (457, 'Capon - Breast, Wing On', 'Predjelo', 44.54, 1494, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (458, 'Fib N9 - Prague Powder', 'Predjelo', 5.92, 1335, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (459, 'Wine - Ice Wine', 'Predjelo', 15.17, 1359, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (460, 'Tea - Vanilla Chai', 'Desert', 10.15, 404, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (461, 'Extract - Vanilla,artificial', 'Glavno jelo', 36.12, 235, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (462, 'Soup - Boston Clam Chowder', 'Desert', 46.62, 321, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (463, 'Chicken - Leg, Fresh', 'Glavno jelo', 18.05, 1921, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (464, 'Coffee - Almond Amaretto', 'Desert', 32.84, 1529, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (465, 'Wine - George Duboeuf Rose', 'Desert', 20.96, 575, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (466, 'Cheese - Goat With Herbs', 'Glavno jelo', 35.52, 1393, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (467, 'Bar - Granola Trail Mix Fruit Nut', 'Glavno jelo', 5.06, 589, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (468, 'Cheese - Le Cru Du Clocher', 'Glavno jelo', 27.11, 249, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (469, 'Potatoes - Yukon Gold, 80 Ct', 'Desert', 40.35, 1702, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (470, 'Soup - Campbells Beef Stew', 'Predjelo', 5.12, 272, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (471, 'Crab Brie In Phyllo', 'Desert', 44.09, 1613, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (472, 'Ocean Spray - Ruby Red', 'Glavno jelo', 6.23, 769, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (473, 'Container - Foam Dixie 12 Oz', 'Glavno jelo', 48.92, 1350, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (474, 'Fish - Soup Base, Bouillon', 'Predjelo', 34.95, 173, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (475, 'Flower - Carnations', 'Glavno jelo', 24.11, 1997, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (476, 'Halibut - Whole, Fresh', 'Predjelo', 10.68, 1932, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (477, 'Cheese Cloth', 'Desert', 25.09, 985, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (478, 'Ostrich - Prime Cut', 'Glavno jelo', 6.67, 1903, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (479, 'Pepper - Orange', 'Glavno jelo', 42.86, 411, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (480, 'Pail With Metal Handle 16l White', 'Desert', 34.4, 1988, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (481, 'Nantuket Peach Orange', 'Predjelo', 13.38, 1781, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (482, 'Coriander - Ground', 'Desert', 15.26, 1158, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (483, 'Pastry - Cherry Danish - Mini', 'Glavno jelo', 7.69, 1078, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (484, 'Tart - Lemon', 'Desert', 31.87, 440, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (485, 'Scallops - 20/30', 'Predjelo', 45.99, 471, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (486, 'Plums - Red', 'Predjelo', 47.01, 562, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (487, 'Liners - Baking Cups', 'Glavno jelo', 21.18, 1082, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (488, 'Aspic - Amber', 'Desert', 32.43, 1023, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (489, 'Cheese - Cambozola', 'Desert', 36.99, 564, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (490, 'Chicken - Whole Fryers', 'Predjelo', 14.89, 1350, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (491, 'Tarts Assorted', 'Glavno jelo', 33.4, 1988, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (492, 'Container - Foam Dixie 12 Oz', 'Glavno jelo', 29.36, 1412, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (493, 'Muffin - Carrot Individual Wrap', 'Glavno jelo', 15.03, 927, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (494, 'Veal - Eye Of Round', 'Predjelo', 7.54, 1944, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (495, 'Lid Coffee Cup 8oz Blk', 'Glavno jelo', 29.38, 691, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (496, 'Carbonated Water - Strawberry', 'Predjelo', 34.78, 1702, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (497, 'Lettuce - Green Leaf', 'Glavno jelo', 13.98, 1743, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (498, 'Beets - Pickled', 'Desert', 41.47, 819, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (499, 'Longos - Grilled Chicken With', 'Glavno jelo', 37.34, 854, false);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (500, 'Mushroom - Morel Frozen', 'Predjelo', 34.87, 658, true);
insert into Dishes (DishID, Name, Category, Price, Calories, IsAvailable) values (501, 'Salmon - Smoked, Sliced', 'Glavno jelo', 41.8, 270, false);
