insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (2, 'Fivespan', 'Quibdó', 48, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (3, 'Topicstorm', 'Ust’ye', 34, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (4, 'Eazzy', 'Gasri', 10, '9:00 AM - 5:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (5, 'Quatz', 'Valuyki', 24, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (6, 'Buzzster', 'Kuala Lumpur', 35, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (7, 'Mynte', 'Yaransk', 38, '9:00 AM - 5:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (8, 'Wikibox', 'Suso', 10, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (9, 'Tagtune', 'Gaoleshan', 37, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (10, 'Snaptags', 'Linjiang', 48, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (11, 'Eazzy', 'Tonkino', 13, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (12, 'Oyondu', 'Pellegrini', 31, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (13, 'Tagfeed', 'Sioux City', 22, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (14, 'Kimia', 'Shifang', 46, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (15, 'Jabberbean', 'Na Thawi', 32, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (16, 'Mycat', 'Huangling', 21, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (17, 'Meedoo', 'Zhukovskiy', 29, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (18, 'Janyx', 'Ningyuan', 12, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (19, 'Edgetag', 'Magisterial', 22, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (20, 'Babbleopia', 'Dawan', 12, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (21, 'Feedfish', 'Ruma', 27, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (22, 'Feedmix', 'Ribeirão Preto', 21, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (23, 'Livepath', 'Foxrock', 37, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (24, 'Vidoo', 'Miðvágur', 29, '9:00 AM - 5:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (25, 'Aimbo', 'Las Carreras', 43, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (26, 'Yodel', 'San Vicente Centenario', 26, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (27, 'Tagpad', 'Qingyun', 15, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (28, 'Lazz', 'Amalfi', 40, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (29, 'Meejo', 'Lipnica', 24, '9:00 AM - 5:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (30, 'Eare', 'Lashio', 19, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (31, 'Gigaclub', 'Piraju', 19, '9:00 AM - 5:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (32, 'Wordpedia', 'Fovissste', 17, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (33, 'Yodel', 'Mentoro Wetan', 41, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (34, 'Skaboo', 'Biny Selo', 13, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (35, 'Realcube', 'Hainan', 36, '9:00 AM - 5:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (36, 'Jayo', 'Yeosu', 50, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (37, 'Abatz', 'West Kelowna', 26, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (38, 'Bluejam', 'Sukamantri Satu', 18, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (39, 'Meejo', 'Khvalovo', 13, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (40, 'Blogspan', 'Pumwani', 46, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (41, 'Lazzy', 'Farkhah', 43, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (42, 'Browseblab', 'Karolinka', 16, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (43, 'Quatz', 'Širvintos', 19, '9:00 AM - 5:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (44, 'Photobug', 'Sukorejo', 38, '9:00 AM - 5:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (45, 'Leexo', 'Podbrdo', 45, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (46, 'Meetz', 'Zmijavci', 38, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (47, 'Rhyzio', 'Sawahbaru', 31, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (48, 'Thoughtmix', 'Taganskiy', 31, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (49, 'Zoomdog', 'Mahajanga', 14, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (50, 'Zazio', 'Akademgorodok', 25, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (51, 'Realbuzz', 'Mchinji', 10, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (52, 'Divanoodle', 'Depapre', 15, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (53, 'Katz', 'Gaoqiao', 43, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (54, 'Yotz', 'Karuk', 15, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (55, 'Thoughtbeat', 'Santa Valha', 48, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (56, 'Eayo', 'Malumfashi', 44, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (57, 'Oyoyo', 'Sanski Most', 22, '9:00 AM - 5:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (58, 'Vidoo', 'Hai’an', 39, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (59, 'Abatz', 'Thap Khlo', 11, '9:00 AM - 5:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (60, 'Thoughtstorm', 'Smyga', 23, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (61, 'Topiczoom', 'Maliang', 41, '9:00 AM - 5:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (62, 'Minyx', 'Pandan Niog', 18, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (63, 'Kwinu', 'Santiaoshi', 14, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (64, 'Pixope', 'Vostryakovo', 39, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (65, 'Yodo', 'Përmet', 34, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (66, 'Gigazoom', 'Fort Wayne', 36, '9:00 AM - 5:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (67, 'Brightdog', 'Kitob', 26, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (68, 'Jaxworks', 'Hehe', 26, '9:00 AM - 5:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (69, 'Thoughtstorm', 'Xiangride', 35, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (70, 'Izio', 'Qaşr al Farāfirah', 25, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (71, 'Myworks', 'Masumbwe', 43, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (72, 'Zoonoodle', 'Kurikka', 10, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (73, 'Livefish', 'Basing', 13, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (74, 'Fadeo', 'Las Junturas', 25, '9:00 AM - 5:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (75, 'Quamba', 'Pustomyty', 43, '9:00 AM - 5:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (76, 'Mynte', 'Osan', 37, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (77, 'Mita', 'Cibuah', 15, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (78, 'Zoomzone', 'Lotoshino', 29, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (79, 'Eabox', 'Shiree', 47, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (80, 'Tazzy', 'Abakaliki', 36, '9:00 AM - 5:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (81, 'Gevee', 'Bang Bo District', 25, '9:00 AM - 5:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (82, 'Topicware', 'Bergen op Zoom', 47, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (83, 'Centizu', 'Kuče', 15, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (84, 'Kazu', 'Porlamar', 34, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (85, 'JumpXS', 'Augustów', 20, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (86, 'Skajo', 'Travesía', 28, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (87, 'Oba', 'Tatou', 27, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (88, 'Topdrive', 'Cikandang', 11, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (89, 'Realcube', 'Xijiadian', 23, '9:00 AM - 5:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (90, 'Oyoloo', 'Shnogh', 22, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (91, 'Quatz', 'Bumpe', 23, '9:00 AM - 5:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (92, 'Youspan', 'Obollo-Afor', 15, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (93, 'Cogilith', 'Kali', 10, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (94, 'Skipstorm', 'Chandra', 45, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (95, 'Youspan', 'Chattanooga', 36, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (96, 'Devbug', 'Ibshawāy', 39, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (97, 'Edgeblab', 'Burgaltay', 11, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (98, 'Vinte', 'Uchimaru', 41, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (99, 'Vipe', 'Jiancha', 18, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (100, 'Meevee', 'Yŏnggwang-ŭp', 19, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (101, 'Tavu', 'Naivasha', 31, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (102, 'Ooba', 'Gaoqiao', 15, '9:00 AM - 5:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (103, 'Youspan', 'Novovolyns’k', 34, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (104, 'Tagopia', 'Xai-Xai', 36, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (105, 'Wordware', 'Vancouver', 26, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (106, 'Yamia', 'Muktāgācha', 40, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (107, 'Kwideo', 'Lhokkruet', 14, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (108, 'Ntags', 'Ciudad Darío', 18, '9:00 AM - 5:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (109, 'Vitz', 'Outeiro', 35, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (110, 'Layo', 'La Unión', 31, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (111, 'Flashdog', 'Puyang', 24, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (112, 'Ainyx', 'Baja Mar', 28, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (113, 'Midel', 'Pingshanhu', 33, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (114, 'Twimbo', 'Gowurdak', 25, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (115, 'Yombu', 'Ciparasi', 43, '9:00 AM - 5:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (116, 'Thoughtstorm', 'Cential', 28, '9:00 AM - 5:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (117, 'Dynava', 'Beicheng', 38, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (118, 'Kamba', 'Dalmeny', 15, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (119, 'Oyondu', 'Zhaizigou', 15, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (120, 'Yata', 'Llacanora', 30, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (121, 'Avamba', 'Turus', 14, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (122, 'Meetz', 'Bagusan', 40, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (123, 'Quatz', 'Wangdain', 18, '9:00 AM - 5:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (124, 'Dabshots', 'Al ‘Āliyah', 44, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (125, 'Geba', 'Malambo', 16, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (126, 'Jabbersphere', 'Tabunok', 36, '9:00 AM - 5:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (127, 'Browsezoom', 'Chojnów', 31, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (128, 'Yozio', 'Bacuyangan', 46, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (129, 'Omba', 'Huangshan', 27, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (130, 'Roomm', 'Inicbulan', 26, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (131, 'BlogXS', 'Fontainebleau', 47, '9:00 AM - 5:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (132, 'Realcube', 'Cumba', 25, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (133, 'Nlounge', 'Rancharia', 36, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (134, 'Chatterbridge', 'Ust’-Labinsk', 48, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (135, 'Meembee', 'Longmen', 15, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (136, 'Skalith', 'General Enrique Mosconi', 40, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (137, 'Tagfeed', 'Thika', 31, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (138, 'Aimbu', 'Wonokerso', 22, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (139, 'Quimm', 'Banjarsari', 48, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (140, 'Zoomdog', 'Nechanice', 29, '9:00 AM - 5:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (141, 'Zoombeat', 'Gongbuxue', 45, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (142, 'Vidoo', 'Bla', 41, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (143, 'Meedoo', 'Zhouhe', 43, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (144, 'Podcat', 'Zeleneč', 43, '9:00 AM - 5:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (145, 'Thoughtbridge', 'Gorna Oryakhovitsa', 13, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (146, 'Brightdog', 'Casisang', 13, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (147, 'Teklist', 'Tiguion', 23, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (148, 'Riffpath', 'Valence', 36, '9:00 AM - 5:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (149, 'Tagopia', 'Jardin', 42, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (150, 'Jabbertype', 'Satita', 20, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (151, 'Mynte', 'Atsipópoulon', 16, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (152, 'Realcube', 'Trpinja', 24, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (153, 'Plambee', 'Blois', 23, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (154, 'Gevee', 'Göteborg', 11, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (155, 'Gigabox', 'Novozavedennoye', 24, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (156, 'Kazu', 'Kuroda', 11, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (157, 'Yambee', 'Magisterial', 39, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (158, 'Kwideo', 'Břeclav', 45, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (159, 'Tanoodle', 'Jaqué', 35, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (160, 'Voolia', 'Borāzjān', 32, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (161, 'Aivee', 'Oefatu', 37, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (162, 'Reallinks', 'Guogan', 41, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (163, 'Demizz', 'Ihosy', 27, '9:00 AM - 5:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (164, 'Twitternation', 'El Puerto', 27, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (165, 'Skippad', 'Batabanó', 50, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (166, 'Fivespan', 'Detupia', 48, '9:00 AM - 5:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (167, 'Browsecat', 'Cigarogol', 15, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (168, 'Demimbu', 'Corpus Christi', 22, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (169, 'Quinu', 'Daba', 14, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (170, 'Ooba', 'Cincinnati', 30, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (171, 'Oyoyo', 'Boise', 12, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (172, 'Flashpoint', 'Tromsø', 17, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (173, 'Snaptags', 'Mangaratiba', 11, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (174, 'Oloo', 'Terentang', 40, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (175, 'Flashpoint', 'Lianrao', 15, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (176, 'Kwilith', 'Itaí', 18, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (177, 'Avaveo', 'Youdian', 23, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (178, 'Linkbridge', 'Citatah Kaler', 49, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (179, 'Youspan', 'San Quintin', 18, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (180, 'Meezzy', 'Caoyan', 49, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (181, 'Teklist', 'Maguwon', 37, '9:00 AM - 5:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (182, 'Eayo', 'Valladolid', 24, '9:00 AM - 5:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (183, 'Kanoodle', 'San Andres', 18, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (184, 'Quinu', 'Borkowice', 16, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (185, 'Blogpad', 'Batu', 45, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (186, 'Skiba', 'Keruguya', 48, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (187, 'Blognation', 'Okpoga', 36, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (188, 'Tagopia', 'Agnibilékrou', 33, '9:00 AM - 5:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (189, 'Digitube', 'Stutterheim', 36, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (190, 'Linkbuzz', 'Tanjungpecinan Utara', 38, '9:00 AM - 5:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (191, 'Wordpedia', 'Changning', 45, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (192, 'Zoovu', 'Pingtan', 22, '9:00 AM - 5:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (193, 'Skiptube', 'Tosontsengel', 15, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (194, 'Browsedrive', 'Boromlya', 16, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (195, 'Tazzy', 'Shuigou’ao', 18, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (196, 'Viva', 'Ar Rubū‘', 24, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (197, 'Thoughtbeat', 'Severodvinsk', 31, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (198, 'Jayo', 'Pamoyanan', 29, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (199, 'Jaxbean', 'Brzozów', 41, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (200, 'Rhyloo', 'Várzea', 33, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (201, 'Flashspan', 'Siikajoki', 26, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (202, 'Avamm', 'Kabar Utara', 32, '9:00 AM - 5:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (203, 'Feedspan', 'Arauca', 32, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (204, 'Centimia', 'Camacha', 42, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (205, 'Fatz', 'Mando', 27, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (206, 'Voomm', 'Granada', 20, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (207, 'Cogibox', 'Butel', 32, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (208, 'Thoughtsphere', 'Xiaojian', 30, '9:00 AM - 5:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (209, 'Demivee', 'Bondo', 11, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (210, 'Meejo', 'San Lucas Sacatepéquez', 30, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (211, 'Aimbo', 'Noyal-sur-Vilaine', 50, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (212, 'Photojam', 'Bonthe', 23, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (213, 'Oyondu', 'Quillabamba', 26, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (214, 'Quimm', 'Solana', 18, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (215, 'Kwilith', 'Shajing', 19, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (216, 'Tagfeed', 'Shabqadar', 26, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (217, 'Jetpulse', 'Wufeng', 10, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (218, 'Zoonoodle', 'Melbourne', 12, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (219, 'Ooba', 'Karanggedang', 12, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (220, 'Youspan', 'Huxi', 36, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (221, 'Linklinks', 'Qiling', 11, '9:00 AM - 5:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (222, 'Vitz', 'Venda do Alcaide', 18, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (223, 'Fadeo', 'Chengdong', 35, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (224, 'Devcast', 'Shanmu', 13, '9:00 AM - 5:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (225, 'Meembee', 'Niandui', 30, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (226, 'Quimm', 'Artsvaberd', 44, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (227, 'Npath', 'Bocana de Paiwas', 47, '9:00 AM - 5:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (228, 'Jayo', 'El Corpus', 35, '9:00 AM - 5:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (229, 'Tanoodle', 'Gudang', 15, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (230, 'DabZ', 'Taibao', 18, '9:00 AM - 5:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (231, 'Blogtags', 'Tamnag', 26, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (232, 'Talane', 'Bełk', 49, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (233, 'Browsedrive', 'Krojo', 30, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (234, 'Wikido', 'Notre Dame', 32, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (235, 'Tanoodle', 'Hīrna', 23, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (236, 'Zoomcast', 'Alvito de São Pedro', 20, '9:00 AM - 5:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (237, 'Rhynoodle', 'Sabanagrande', 20, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (238, 'Plambee', 'Karagandy', 17, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (239, 'Camido', 'Novaya Tavolzhanka', 44, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (240, 'Kwilith', 'Nikitinskiy', 17, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (241, 'Edgeclub', 'Södertälje', 15, '9:00 AM - 5:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (242, 'Yata', 'Hulín', 24, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (243, 'Aimbu', 'Vergara', 28, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (244, 'Dabfeed', 'Bulu', 27, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (245, 'Oloo', 'Kamloops', 34, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (246, 'Katz', 'Chubek', 12, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (247, 'Skidoo', 'Negotino', 46, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (248, 'Trudoo', 'Jintang', 11, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (249, 'Realfire', 'Zhdanov', 36, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (250, 'Rhynyx', 'Chitagá', 24, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (251, 'Realpoint', 'Mgandu', 41, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (252, 'Skilith', 'Tadou', 32, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (253, 'Geba', 'Lunsar', 41, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (254, 'Edgetag', 'Cabeço de Vide', 17, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (255, 'Agimba', 'Shilibu', 11, '9:00 AM - 5:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (256, 'Fiveclub', 'Benniu', 35, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (257, 'Buzzbean', 'Xiaoduchuan', 19, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (258, 'Kayveo', 'Lampa', 47, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (259, 'Livefish', 'Jinhe', 17, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (260, 'Photobean', 'Pora', 16, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (261, 'Zoonder', 'La Paz', 45, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (262, 'Fiveclub', 'Fengtai', 31, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (263, 'Topicblab', 'Kuala Terengganu', 10, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (264, 'Myworks', 'Cikaung', 12, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (265, 'Jetwire', 'Uliastay', 31, '9:00 AM - 5:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (266, 'Midel', 'Gradačac', 42, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (267, 'Youopia', 'Šimanovci', 24, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (268, 'Zoovu', 'Tunasbaru', 23, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (269, 'Roombo', 'Žďár', 37, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (270, 'Quatz', 'Gostyń', 22, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (271, 'Quimba', 'Xiaxi', 20, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (272, 'Zava', 'Itapeva', 10, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (273, 'Zoombeat', 'Mineiros', 33, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (274, 'Shufflebeat', 'Hermosa', 23, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (275, 'Riffpedia', 'Athens', 14, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (276, 'Skaboo', 'Mangusu', 29, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (277, 'Kwideo', 'Dadu', 15, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (278, 'Buzzbean', 'Caujul', 11, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (279, 'Dynava', 'Menzel Abderhaman', 25, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (280, 'Thoughtsphere', 'Kananga', 19, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (281, 'Skiba', 'Tulsīpur', 43, '9:00 AM - 5:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (282, 'Skipstorm', 'Sam Roi Yot', 24, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (283, 'Riffpedia', 'Sudimara', 21, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (284, 'Skilith', 'Oguta', 33, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (285, 'Babblestorm', 'Maracha', 45, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (286, 'Jaxnation', 'Banjar Batuaji Kaja', 39, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (287, 'Plajo', 'Paris 09', 28, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (288, 'Zoovu', 'Clodomira', 18, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (289, 'Flipstorm', 'Mpulungu', 29, '9:00 AM - 5:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (290, 'Viva', 'Bofuer', 18, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (291, 'Jabbersphere', 'Orlando', 30, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (292, 'Feedspan', 'Lysekil', 45, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (293, 'Photobean', 'Bergen', 48, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (294, 'Bluezoom', 'Farah', 37, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (295, 'Wikizz', 'Villa Regina', 37, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (296, 'Minyx', 'Stari Kuty', 36, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (297, 'Zoomdog', 'Lieksa', 37, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (298, 'Twimbo', 'Villa Ángela', 13, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (299, 'Quire', 'Brezovica', 41, '9:00 AM - 5:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (300, 'Meedoo', 'New Orleans', 48, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (301, 'Meetz', 'Rahayu', 42, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (302, 'Shufflebeat', 'Taurage', 44, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (303, 'Abata', 'Yantian', 17, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (304, 'Twinder', 'Gangmian', 32, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (305, 'Kare', 'Lopez Jaena', 22, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (306, 'Talane', 'Sibulan', 21, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (307, 'Kwideo', 'Kadugannawa', 26, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (308, 'Tagopia', 'Itapeva', 29, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (309, 'Centizu', 'Brčko', 47, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (310, 'Wikizz', 'Nambak Tengah', 34, '9:00 AM - 5:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (311, 'Trunyx', 'Cochadas', 25, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (312, 'Wikibox', 'Banjar Swastika', 27, '9:00 AM - 5:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (313, 'Thoughtworks', 'Malibong East', 28, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (314, 'Gevee', 'Lokot’', 49, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (315, 'Bluezoom', 'Mufulira', 42, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (316, 'Ozu', 'Ključ', 23, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (317, 'Zoonoodle', 'Begang', 22, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (318, 'Voolith', 'Huangling', 16, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (319, 'Zazio', 'Tučepi', 44, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (320, 'Topdrive', 'Issy-les-Moulineaux', 19, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (321, 'Tekfly', 'Mramani', 37, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (322, 'Lazzy', 'Podujeva', 50, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (323, 'Quatz', 'Isnos', 37, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (324, 'Thoughtsphere', 'Suphan Buri', 47, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (325, 'Teklist', 'Banī Walīd', 24, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (326, 'Ntag', 'Balingasag', 14, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (327, 'Babbleset', 'Kodyma', 44, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (328, 'Zoombeat', 'Guaçuí', 33, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (329, 'Cogilith', 'Smyga', 17, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (330, 'Babbleset', 'Visby', 25, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (331, 'Devify', 'Sastöbe', 24, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (332, 'Yata', 'Pedro Juan Caballero', 28, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (333, 'Youfeed', 'Kalāt', 21, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (334, 'Browsecat', 'Changbu', 30, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (335, 'Eadel', 'Watergrasshill', 27, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (336, 'Tazzy', 'Nîmes', 41, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (337, 'Thoughtbeat', 'Aleysk', 50, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (338, 'Feedspan', 'Gangkoujie', 21, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (339, 'Mydeo', 'Santa Bárbara', 47, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (340, 'Gigabox', 'Tugu', 30, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (341, 'Yakijo', 'Borodinskiy', 44, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (342, 'Thoughtmix', 'Cà Mau', 38, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (343, 'Eamia', 'Naberezhnyye Chelny', 45, '9:00 AM - 5:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (344, 'Dynazzy', 'Stoszowice', 40, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (345, 'Brainsphere', 'Kuzhu', 17, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (346, 'Skimia', 'Santo Ângelo', 10, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (347, 'Chatterpoint', 'Nāgarpur', 43, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (348, 'Youspan', 'Hitoyoshi', 24, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (349, 'Talane', 'Los Lotes', 47, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (350, 'Twitterworks', 'Toktogul', 46, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (351, 'Youbridge', 'Samokov', 29, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (352, 'Meembee', 'Ashford', 14, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (353, 'Babbleset', 'Västra Frölunda', 40, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (354, 'Janyx', 'Ganchazi', 13, '9:00 AM - 5:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (355, 'Oyondu', 'Tatariv', 18, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (356, 'Layo', 'Rio Claro', 38, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (357, 'Buzzster', 'Islāmkot', 44, '9:00 AM - 5:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (358, 'Abata', 'Jiegan', 22, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (359, 'Dynabox', 'Titao', 27, '9:00 AM - 5:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (360, 'Jabbersphere', 'Rakek', 41, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (361, 'Jabbersphere', 'Al Maşlūb', 13, '9:00 AM - 5:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (362, 'Divanoodle', 'Xintang', 44, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (363, 'Edgeblab', 'Weibin', 21, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (364, 'LiveZ', 'Nangang', 35, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (365, 'Flashspan', 'Litian', 32, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (366, 'Gabcube', 'Almeria', 37, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (367, 'Oozz', 'Castro Barros', 34, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (368, 'Zazio', 'Taoyuan', 22, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (369, 'Buzzshare', 'El Calvario', 41, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (370, 'Babblestorm', 'Gandajika', 41, '9:00 AM - 5:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (371, 'Brainbox', 'Gaojia', 10, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (372, 'Jabberbean', 'Solna', 50, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (373, 'Jabberstorm', 'Yongfu', 25, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (374, 'Skinder', 'Néo Psychikó', 23, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (375, 'Tagfeed', 'Trondheim', 22, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (376, 'Dabtype', 'Auxerre', 29, '9:00 AM - 5:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (377, 'Meevee', 'Hong’an Chengguanzhen', 19, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (378, 'Talane', 'Puro', 42, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (379, 'Vinte', 'Juvisy-sur-Orge', 29, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (380, 'LiveZ', 'Burns Lake', 18, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (381, 'Katz', 'Pesisir', 40, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (382, 'Linklinks', 'Dahe', 14, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (383, 'Photospace', 'Besko', 18, '9:00 AM - 5:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (384, 'Skaboo', 'Khánh Hải', 45, '9:00 AM - 5:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (385, 'Zoomlounge', 'Falënki', 14, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (386, 'Gigazoom', 'Iraray', 35, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (387, 'Kwideo', 'Buga', 33, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (388, 'Skajo', 'Nuevo Arraiján', 45, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (389, 'Tekfly', 'Angra do Heroísmo', 31, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (390, 'Katz', 'Lyalichi', 38, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (391, 'Photospace', 'Nancy', 27, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (392, 'Kanoodle', 'Póvoa', 46, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (393, 'Kaymbo', 'Wysoka', 12, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (394, 'Realblab', 'Athlone', 15, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (395, 'Browseblab', 'Sada', 42, '9:00 AM - 5:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (396, 'Photobug', 'Comallo', 18, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (397, 'Camimbo', 'Ngala', 48, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (398, 'Eazzy', 'Bestöbe', 36, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (399, 'Skipfire', 'Krajan', 13, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (400, 'Rhyloo', 'Stockholm', 46, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (401, 'Dabjam', 'Nyeri', 30, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (402, 'Lazzy', 'Komyshany', 42, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (403, 'Quinu', 'Facatativá', 21, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (404, 'Devify', 'Waikambila', 20, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (405, 'Zoomdog', 'Buenos Aires', 39, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (406, 'Kazu', 'Rennes', 32, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (407, 'Buzzbean', 'Batojaran', 31, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (408, 'Youspan', 'Jintang', 39, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (409, 'Wikido', 'Šumice', 10, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (410, 'Centidel', 'Chantilly', 49, '9:00 AM - 5:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (411, 'Dabshots', 'Pernå', 31, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (412, 'Skippad', 'As Suwaydā', 42, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (413, 'Centimia', 'Lidian', 23, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (414, 'Voomm', 'Chambishi', 15, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (415, 'Aibox', 'Tangwāni', 19, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (416, 'Demimbu', 'Göteborg', 35, '9:00 AM - 5:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (417, 'Jaxspan', 'Kítsi', 16, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (418, 'Izio', 'Changshu City', 27, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (419, 'Eare', 'Nässjö', 42, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (420, 'Gigashots', 'Kai', 46, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (421, 'Dabjam', 'Tarata', 23, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (422, 'Cogibox', 'Abreus', 47, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (423, 'Plambee', 'Kota Kinabalu', 14, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (424, 'Jabbersphere', 'Xiangshui', 48, '9:00 AM - 5:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (425, 'DabZ', 'Finiq', 37, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (426, 'Chatterpoint', 'Bianzhuang', 13, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (427, 'Quaxo', 'Balungkopi', 21, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (428, 'Photobean', 'Kario', 50, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (429, 'Babbleopia', 'Bang Saphan', 26, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (430, 'Flipopia', 'Tambulig', 49, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (431, 'InnoZ', 'Gritsovskiy', 44, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (432, 'Fivechat', 'Täby', 38, '9:00 AM - 5:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (433, 'Mycat', 'Xiashuitou', 35, '9:00 AM - 5:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (434, 'Devbug', 'Shibetsu', 50, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (435, 'Thoughtbeat', 'Zanjān', 23, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (436, 'Realbuzz', 'Corticeiro de Baixo', 25, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (437, 'Ooba', 'Lindesberg', 46, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (438, 'Pixonyx', 'Amberd', 15, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (439, 'Rhynoodle', 'Maketu', 17, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (440, 'Omba', 'Las Animas', 42, '9:00 AM - 5:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (441, 'Tavu', 'Tisul’', 21, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (442, 'Dabtype', 'Ishimbay', 40, '9:00 AM - 5:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (443, 'Brightbean', 'Yongchang', 36, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (444, 'Babbleset', 'Isheyevka', 32, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (445, 'Meemm', 'Löddeköpinge', 35, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (446, 'Ainyx', 'Zabierzów', 10, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (447, 'Oyondu', 'Minle', 37, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (448, 'Kazio', 'Huating', 20, '9:00 AM - 5:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (449, 'Browseblab', 'Azilal', 27, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (450, 'Wikivu', 'Bendo', 28, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (451, 'Twimbo', 'Glafirovka', 40, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (452, 'Dynava', 'Tumpang Satu', 21, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (453, 'Flashspan', 'Paris La Défense', 21, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (454, 'Yabox', 'Lysyanka', 44, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (455, 'Trilia', 'Acton Vale', 45, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (456, 'Bubbletube', 'Gaotan', 38, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (457, 'Oyoloo', 'Ad Dasmah', 21, '9:00 AM - 5:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (458, 'Abata', 'Tulsa', 37, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (459, 'Reallinks', 'Saint-Bruno', 39, '9:00 AM - 5:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (460, 'Centizu', 'Pangushan', 19, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (461, 'Edgepulse', 'Awsīm', 46, '9:00 AM - 5:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (462, 'Skipstorm', 'Mancogeh', 12, '9:00 AM - 5:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (463, 'Topicshots', 'Staraya Derevnya', 20, '9:00 AM - 5:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (464, 'Skidoo', 'Båstad', 10, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (465, 'Demizz', 'Lima Pampa', 41, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (466, 'Demimbu', 'Belovodskoye', 37, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (467, 'InnoZ', 'Samburat', 39, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (468, 'Riffwire', 'Riosucio', 43, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (469, 'Meevee', 'Valença', 22, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (470, 'Pixope', 'Santa Rosa de Viterbo', 34, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (471, 'Buzzbean', 'Pavino', 17, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (472, 'Realpoint', 'Mitry-Mory', 42, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (473, 'Realpoint', 'Pinheiral', 26, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (474, 'Zoombox', 'Weifen', 11, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (475, 'Livepath', 'Tanumshede', 47, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (476, 'Camimbo', 'Liuhe', 48, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (477, 'Lazzy', 'Olho Marinho', 36, '9:00 AM - 5:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (478, 'Podcat', 'Colotenango', 26, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (479, 'Devshare', 'Buriram', 40, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (480, 'Kazio', 'Huangshui', 11, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (481, 'Realblab', 'Kozmice', 11, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (482, 'Tagchat', 'Omu Aran', 42, '9:00 AM - 5:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (483, 'Yakijo', 'Nanto-shi', 36, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (484, 'Twitterwire', 'Keda', 26, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (485, 'Topicblab', 'Daultāla', 42, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (486, 'Camido', 'Nariño', 18, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (487, 'Skidoo', 'Tornio', 24, '9:00 AM - 5:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (488, 'Mynte', 'Oslo', 24, '9:00 AM - 5:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (489, 'Oodoo', 'Dongtuan', 31, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (490, 'Oyonder', 'Montauban', 40, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (491, 'Skinte', 'Balfour', 36, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (492, 'Tavu', 'Sydney', 38, '9:00 AM - 5:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (493, 'Meevee', 'Kuala Lumpur', 33, '7:30 AM - 3:30 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (494, 'Innotype', 'Bang Ban', 38, '8:00 AM - 4:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (495, 'Camido', 'Madīnat ‘Īsá', 49, '11:00 AM - 7:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (496, 'Kaymbo', 'Jinanten', 20, '10:00 AM - 6:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (497, 'Rooxo', 'Brzozów', 19, '9:00 AM - 5:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (498, 'Realcube', 'Moutas', 21, '9:00 AM - 5:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (499, 'Mynte', 'Shambu', 23, '9:00 AM - 5:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (500, 'Yambee', 'San Felipe', 22, '9:00 AM - 5:00 PM');
insert into Restaurants (RestaurantID, Name, City, Capacity, WorkingHours) values (501, 'Thoughtbridge', 'Sremska Mitrovica', 32, '11:00 AM - 7:00 PM');